import { Prophecy, ProphecyCategory } from '../types';

/* 
  Datenbank der messianischen Prophetien (50 Einträge)
  Aktualisiert gemäß Benutzeranforderung für Nr. 3, 5, 23 und theologischen Kontext.
  Alle Bibel-Links verweisen auf bibleserver.com (SCH2000 oder ELB).
*/

export const prophecies: Prophecy[] = [
  // --- HERKUNFT & GEBURT ---
  {
    id: 1,
    kategorie: ProphecyCategory.GEBURT,
    beschreibung: "Der Messias wird in Bethlehem Efrata geboren werden.",
    ot_stelle: "Micha 5,1",
    ot_text_kurz: "Und du, Bethlehem-Ephrata, zu klein, um unter den Tausenden von Juda zu sein, aus dir wird mir hervorkommen, der Herrscher über Israel sein soll.",
    ot_zeitraum: "ca. 700 v. Chr.",
    nt_stelle: "Matthäus 2,1",
    nt_text_kurz: "Als aber Jesus zu Bethlehem in Judäa geboren war, in den Tagen Herodes', des Königs...",
    kommentar: "Gott wählte bewusst das kleine Bethlehem aus, um zu zeigen, dass seine Macht im Geringen offenbar wird. Die Spezifizierung 'Efrata' unterscheidet diesen Ort klar von einem anderen Bethlehem im Norden Israels.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Micha5%2C1"],
    tags: ["Messias", "Geburt", "Ort", "Präzision"]
  },
  {
    id: 2,
    kategorie: ProphecyCategory.GEBURT,
    beschreibung: "Der Messias wird von einer Jungfrau geboren.",
    ot_stelle: "Jesaja 7,14",
    ot_text_kurz: "Darum wird euch der Herr selbst ein Zeichen geben: Siehe, die Jungfrau wird schwanger werden und einen Sohn gebären...",
    ot_zeitraum: "ca. 735 v. Chr.",
    nt_stelle: "Matthäus 1,22-23",
    nt_text_kurz: "Dies alles aber ist geschehen, damit erfüllt würde ... Siehe, die Jungfrau wird schwanger sein...",
    nt_2_stelle: "Lukas 1,34-35",
    nt_2_text_kurz: "Maria aber sprach zu dem Engel: Wie wird dies zugehen, da ich von keinem Mann weiß? Und der Engel antwortete und sprach zu ihr: Der Heilige Geist wird über dich kommen, und Kraft des Höchsten wird dich überschatten; darum wird auch das Heilige, das geboren werden wird, Sohn Gottes genannt werden.",
    kommentar: "Die Jungfrauengeburt ist die Voraussetzung dafür, dass Jesus sowohl wahrer Gott als auch sündloser Mensch ist. Ohne menschlichen Vater wurde die Kette der Erbsünde unterbrochen.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Jesaja7%2C14"],
    tags: ["Jungfrauengeburt", "Immanuel", "Sohn Gottes"]
  },
  {
    id: 3,
    kategorie: ProphecyCategory.HERKUNFT,
    beschreibung: "Er stammt aus dem Stamm Juda.",
    ot_stelle: "1. Mose 49,10",
    ot_text_kurz: "Nicht weichen wird das Zepter von Juda, noch ein Herrscherstab zwischen seinen Füßen hinweg, bis dass Schilo kommt, und ihm werden die Völker gehorchen.",
    ot_zeitraum: "ca. 1600 v. Chr.",
    nt_stelle: "Lukas 3,23-38",
    nt_text_kurz: "Und er war, wie man meinte, ein Sohn des Joseph... des Aminadab, des Perez, des Juda...",
    nt_2_stelle: "Matthäus 1,1-3",
    nt_2_text_kurz: "Dies ist das Buch von der Geschichte Jesu Christi, des Sohnes Davids, des Sohnes Abrahams. Abraham zeugte Isaak. Isaak zeugte Jakob. Jakob zeugte Juda und seine Brüder. Juda zeugte Perez und Serach mit der Tamar …",
    kommentar: "Die Abstammung aus Juda bestätigt das königliche Anrecht Jesu. Das Wort 'Schilo' wurde seit jeher messianisch verstanden. Jesu Stammbaum dokumentiert die Treue Gottes über Jahrtausende hinweg.",
    quelle_links: ["https://www.bibleserver.com/ELB/Lukas3%2C33", "https://www.bibleserver.com/SCH2000/Matth%C3%A4us1%2C1-3"],
    tags: ["Stammbaum", "Juda", "Königtum"]
  },
  {
    id: 4,
    kategorie: ProphecyCategory.DIENST,
    beschreibung: "Dem Messias wird ein Wegbereiter vorausgehen.",
    ot_stelle: "Jesaja 40,3",
    ot_text_kurz: "Stimme eines Rufenden in der Wüste: Bereitet den Weg des Herrn.",
    ot_2_stelle: "Maleachi 3,1",
    ot_2_text_kurz: "Siehe, ich sende meinen Boten, dass er den Weg bahne vor mir her.",
    ot_zeitraum: "ca. 700 v. Chr.",
    nt_stelle: "Matthäus 3,3",
    nt_text_kurz: "Das ist der, von welchem durch den Propheten Jesaja gesagt ist: Eine Stimme ruft in der Wüste...",
    nt_2_stelle: "Lukas 1,17",
    nt_2_text_kurz: "Und er wird vor ihm hergehen im Geist und in der Kraft des Elia.",
    kommentar: "Johannes der Täufer war die 'Stimme', die das Volk zur Buße aufrief. Seine Botschaft bereitete die Herzen der Menschen auf das Erscheinen des Retters vor.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Jesaja40%2C3"],
    tags: ["Johannes der Täufer", "Buße", "Wegbereiter"]
  },
  {
    id: 5,
    kategorie: ProphecyCategory.KOENIGTUM,
    beschreibung: "Einzug in Jerusalem auf einem Esel.",
    ot_stelle: "Sacharja 9,9",
    ot_text_kurz: "Juble laut, Tochter Zion! ... Siehe, dein König kommt zu dir ... demütig und reitet auf einem Esel.",
    ot_zeitraum: "ca. 520 v. Chr.",
    nt_stelle: "Lukas 19,29-35",
    nt_text_kurz: "Und sie brachten es zu Jesus und warfen ihre Kleider auf das Füllen und setzten Jesus darauf.",
    kommentar: "Der Messias kommt nicht als kriegerischer Eroberer auf einem Ross, sondern als Friedenskönig auf einem Lasttier. Dies symbolisiert seine Sanftmut und die geistliche Natur seines Reiches.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Sacharja9%2C9", "https://www.bibleserver.com/SCH2000/Lukas19%2C29-35"],
    tags: ["Palmsonntag", "Demut", "König", "Frieden"]
  },
  {
    id: 6,
    kategorie: ProphecyCategory.LEIDEN,
    beschreibung: "Verraten für 30 Silberlinge.",
    ot_stelle: "Sacharja 11,12",
    ot_text_kurz: "Da wogen sie meinen Lohn ab: 30 Silberlinge.",
    ot_zeitraum: "ca. 520 v. Chr.",
    nt_stelle: "Matthäus 26,15",
    nt_text_kurz: "Und er sprach: Was wollt ihr mir geben, so will ich ihn euch verraten? Und sie zahlten ihm 30 Silberlinge.",
    kommentar: "30 Silberlinge waren der gesetzliche Preis für einen Sklaven. Der Schöpfer des Universums ließ sich zum Preis eines Sklaven verraten, um uns aus der Sklaverei der Sünde zu erkaufen.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Sacharja11%2C12"],
    tags: ["Verrat", "Judas", "Preis", "Silber"]
  },
  {
    id: 7,
    kategorie: ProphecyCategory.LEIDEN,
    beschreibung: "Das Geld wird dem Töpfer hingeworfen.",
    ot_stelle: "Sacharja 11,13",
    ot_text_kurz: "Und ich nahm die 30 Silberlinge und warf sie ins Haus des HERRN für den Töpfer.",
    ot_zeitraum: "ca. 520 v. Chr.",
    nt_stelle: "Matthäus 27,5-7",
    nt_text_kurz: "Und er warf die Silberlinge in den Tempel... Sie hielten aber Rat und kauften dafür den Acker des Töpfers.",
    kommentar: "Die erstaunliche Übereinstimmung von Betrag, Ort (Tempel) und Verwendung (Töpfer) beweist die göttliche Inspiration der Heiligen Schrift über Jahrhunderte hinweg.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Matth%C3%A4us27%2C5-7"],
    tags: ["Präzision", "Gottes Wort", "Töpferacker"]
  },
  {
    id: 8,
    kategorie: ProphecyCategory.LEIDEN,
    beschreibung: "Er schweigt vor seinen Anklägern.",
    ot_stelle: "Jesaja 53,7",
    ot_text_kurz: "Er wurde misshandelt, aber er beugte sich und tat seinen Mund nicht auf, wie ein Lamm, das zur Schlachtbank geführt wird.",
    ot_zeitraum: "ca. 700 v. Chr.",
    nt_stelle: "Matthäus 27,12-14",
    nt_text_kurz: "Und als er von den Hohenpriestern und Ältesten verklagt wurde, antwortete er nichts.",
    kommentar: "Jesu Schweigen war kein Zeichen von Schwäche, sondern von souveräner Hingabe. Er verteidigte sich nicht, weil er bereit war, das Urteil für unsere Sünden auf sich zu nehmen.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Jesaja53%2C7"],
    tags: ["Demut", "Hingabe", "Gericht"]
  },
  {
    id: 9,
    kategorie: ProphecyCategory.TOD,
    beschreibung: "Hände und Füße durchgraben (Kreuzigung).",
    ot_stelle: "Psalm 22,17",
    ot_text_kurz: "Denn Hunde haben mich umgeben... Sie haben meine Hände und meine Füße durchgraben.",
    ot_zeitraum: "ca. 1000 v. Chr.",
    nt_stelle: "Johannes 19,18",
    nt_text_kurz: "Wo sie ihn kreuzigten und zwei andere mit ihm...",
    nt_2_stelle: "Johannes 20,25",
    nt_2_text_kurz: "Wenn ich nicht in seinen Händen das Nägelmal sehe...",
    kommentar: "Psalm 22 beschreibt die Qualen der Kreuzigung, bevor diese Hinrichtungsart überhaupt erfunden war. Dies zeigt, dass Jesus das Lamm Gottes ist, das vor Grundlegung der Welt bestimmt war.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Psalm22%2C17"],
    tags: ["Kreuzigung", "Leiden", "Durchbohrt"]
  },
  {
    id: 10,
    kategorie: ProphecyCategory.TOD,
    beschreibung: "Er wird bei einem Reichen begraben.",
    ot_stelle: "Jesaja 53,9",
    ot_text_kurz: "Und man bestimmte sein Grab bei Gottlosen, aber bei einem Reichen war er in seinem Tod.",
    ot_zeitraum: "ca. 700 v. Chr.",
    nt_stelle: "Matthäus 27,57-60",
    nt_text_kurz: "Da kam ein reicher Mann von Arimathäa namens Joseph ... und legte ihn in sein neues Grab.",
    kommentar: "Selbst im Tod sorgte Gott für die Würde seines Sohnes. Die Erfüllung durch Joseph von Arimathäa war ein sichtbares Zeichen gegen die Schande des Kreuzes.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Matth%C3%A4us27%2C57-60"],
    tags: ["Begräbnis", "Joseph von Arimathäa", "Ehre"]
  },
  {
    id: 11,
    kategorie: ProphecyCategory.TOD,
    beschreibung: "Kein Knochen soll ihm zerbrochen werden.",
    ot_stelle: "Psalm 34,21",
    ot_text_kurz: "Er bewahrt ihm alle seine Gebeine, nicht eines von ihnen wird zerbrochen.",
    ot_2_stelle: "2. Mose 12,46",
    ot_2_text_kurz: "Ihr sollt keinen Knochen an ihm (dem Passahlamm) zerbrechen.",
    ot_zeitraum: "ca. 1000 v. Chr.",
    nt_stelle: "Johannes 19,32-33",
    nt_text_kurz: "Da kamen die Soldaten und brachen dem ersten die Beine... Als sie aber zu Jesus kamen und sahen, dass er schon gestorben war, zerschlugen sie ihm die Beine nicht.",
    kommentar: "Jesus ist das wahre Passahlamm. Seine Unversehrtheit am Kreuz bestätigt, dass er das perfekte Opfer ohne Makel ist, dessen Tod uns vor dem Gericht rettet.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Johannes19%2C33"],
    tags: ["Passahlamm", "Opfer", "Typologie"]
  },
  {
    id: 12,
    kategorie: ProphecyCategory.AUFERSTEHUNG,
    beschreibung: "Er wird nicht im Tod bleiben (Auferstehung).",
    ot_stelle: "Psalm 16,10",
    ot_text_kurz: "Denn du wirst meine Seele nicht dem Totenreich preisgeben und nicht zulassen, dass dein Getreuer die Verwesung sieht.",
    ot_zeitraum: "ca. 1000 v. Chr.",
    nt_stelle: "Apostelgeschichte 2,31",
    nt_text_kurz: "Hat er vorausschauend von der Auferstehung des Christus geredet...",
    kommentar: "Die Auferstehung ist der Beweis dafür, dass Jesu Opfer von Gott angenommen wurde. Er hat den Tod besiegt und ist der Garant für unser ewiges Leben.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Psalm16%2C10"],
    tags: ["Auferstehung", "Sieg", "Leben"]
  },
  {
    id: 13,
    kategorie: ProphecyCategory.LEIDEN,
    beschreibung: "Sie geben ihm Galle und Essig zu trinken.",
    ot_stelle: "Psalm 69,22",
    ot_text_kurz: "Und sie gaben mir Galle zur Speise und Essig zu trinken in meinem Durst.",
    ot_zeitraum: "ca. 1000 v. Chr.",
    nt_stelle: "Matthäus 27,34",
    nt_text_kurz: "Da gaben sie ihm Essig mit Galle vermischt zu trinken; und als er es kostete, wollte er nicht trinken.",
    kommentar: "Selbst in den kleinsten Details seines Leidens wurde Jesus nicht verschont. Diese Prophetie unterstreicht die Bitterkeit des Kelches, den er für uns trank.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Psalm69%2C22"],
    tags: ["Durst", "Bitternis", "Leiden"]
  },
  {
    id: 14,
    kategorie: ProphecyCategory.TOD,
    beschreibung: "Dunkelheit am Tag.",
    ot_stelle: "Amos 8,9",
    ot_text_kurz: "Und es soll geschehen an jenem Tag ... da will ich die Sonne am Mittag untergehen lassen.",
    ot_zeitraum: "ca. 760 v. Chr.",
    nt_stelle: "Matthäus 27,45",
    nt_text_kurz: "Aber von der sechsten Stunde an kam eine Finsternis über das ganze Land bis zur neunten Stunde.",
    kommentar: "Die Finsternis am Kreuz war ein kosmisches Zeichen des Zorns Gottes über die Sünde, die Jesus stellvertretend trug. Gott verbarg sein Angesicht in der Stunde des Gerichts.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Amos8%2C9"],
    tags: ["Finsternis", "Gericht", "Zeichen"]
  },
  {
    id: 15,
    kategorie: ProphecyCategory.AUFERSTEHUNG,
    beschreibung: "Himmelfahrt: Er ist aufgefahren in die Höhe.",
    ot_stelle: "Psalm 68,19",
    ot_text_kurz: "Du bist zur Höhe emporgestiegen, hast Gefangene weggeführt...",
    ot_zeitraum: "ca. 1000 v. Chr.",
    nt_stelle: "Lukas 24,51",
    nt_text_kurz: "Und es geschah, indem er sie segnete, schied er von ihnen und wurde aufgehoben in den Himmel.",
    kommentar: "Jesu Himmelfahrt markiert seine Rückkehr zur Herrlichkeit des Vaters. Von dort aus regiert er und tritt als unser Hohepriester für uns ein.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Psalm68%2C19"],
    tags: ["Himmelfahrt", "Herrlichkeit", "Thron"]
  },
  {
    id: 16,
    kategorie: ProphecyCategory.HERKUNFT,
    beschreibung: "Nachkomme Abrahams: Segen für alle Völker.",
    ot_stelle: "1. Mose 22,18",
    ot_text_kurz: "Und in deinem Samen sollen alle Völker der Erde gesegnet werden.",
    ot_zeitraum: "ca. 2000 v. Chr.",
    nt_stelle: "Apostelgeschichte 3,25",
    nt_text_kurz: "...in deinem Samen sollen gesegnet werden alle Geschlechter der Erde.",
    kommentar: "Durch Jesus Christus wurde der Bund mit Abraham weltweit wirksam. Nicht mehr nur ein Volk, sondern Menschen aus allen Nationen finden durch ihn Versöhnung mit Gott.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/1.Mose22%2C18"],
    tags: ["Abraham", "Segen", "Völker"]
  },
  {
    id: 17,
    kategorie: ProphecyCategory.HERKUNFT,
    beschreibung: "Nachkomme Isaaks: Erbe der Verheißung.",
    ot_stelle: "1. Mose 17,19",
    ot_text_kurz: "Nein, sondern Sara ... soll dir einen Sohn gebären ... und ich werde meinen Bund mit ihm aufrichten.",
    ot_zeitraum: "ca. 2000 v. Chr.",
    nt_stelle: "Matthäus 1,2",
    nt_text_kurz: "Abraham zeugte den Isaak, Isaak zeugte den Jakob...",
    kommentar: "Die Linie des Messias wurde durch Gottes Wahl eingeschränkt. Gott bestimmt den Weg des Heils und bewahrt seine Zusage über Generationen hinweg.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Matth%C3%A4us1%2C2"],
    tags: ["Isaak", "Bund", "Wahl"]
  },
  {
    id: 18,
    kategorie: ProphecyCategory.HERKUNFT,
    beschreibung: "Nachkomme Jakobs: Ein Stern aus Jakob.",
    ot_stelle: "4. Mose 24,17",
    ot_text_kurz: "Ich sehe ihn, aber nicht jetzt ... Es wird ein Stern aus Jakob aufgehen.",
    ot_zeitraum: "ca. 1400 v. Chr.",
    nt_stelle: "Lukas 3,34",
    nt_text_kurz: "...Sohn des Jakob, Sohn des Isaak, Sohn des Abraham.",
    kommentar: "Das Bild des Sterns weist auf die königliche Erhabenheit und göttliche Herkunft des Retters hin. Jesus ist der Morgenstern, der das Ende der geistlichen Nacht ankündigt.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/4.Mose24%2C17"],
    tags: ["Jakob", "Stern", "Licht"]
  },
  {
    id: 19,
    kategorie: ProphecyCategory.HERKUNFT,
    beschreibung: "Nachkomme König Davids: Der ewige Thron.",
    ot_stelle: "Jesaja 11,1",
    ot_text_kurz: "Und es wird ein Reis hervorgehen aus dem Stamm Isais.",
    ot_zeitraum: "ca. 700 v. Chr.",
    nt_stelle: "Matthäus 1,1",
    nt_text_kurz: "Geschlechtsregister Jesu Christi, des Sohnes Davids...",
    kommentar: "Jesus ist der rechtmäßige Erbe des Thrones Davids. Seine Herrschaft ist jedoch nicht irdisch begrenzt, sondern ein ewiges Königreich der Gerechtigkeit.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Jesaja11%2C1"],
    tags: ["David", "Thron", "Wurzel"]
  },
  {
    id: 20,
    kategorie: ProphecyCategory.GEBURT,
    beschreibung: "Kindermassaker bei seiner Geburt.",
    ot_stelle: "Jeremia 31,15",
    ot_text_kurz: "Man hört eine Stimme in Rama, Wehklage und bitteres Weinen; Rahel weint um ihre Kinder...",
    ot_zeitraum: "ca. 600 v. Chr.",
    nt_stelle: "Matthäus 2,16",
    nt_text_kurz: "Da ergrimmte Herodes sehr ... und ließ alle Knaben töten.",
    kommentar: "Das Leiden bei Jesu Geburt zeigt den Hass der Welt und des Satans gegen den Retter. Doch Gottes Plan ließ sich durch menschliche Grausamkeit nicht vereiteln.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Jeremia31%2C15"],
    tags: ["Leid", "Widerstand", "Bewahrung"]
  },
  {
    id: 21,
    kategorie: ProphecyCategory.GEBURT,
    beschreibung: "Der Messias wird aus Ägypten gerufen.",
    ot_stelle: "Hosea 11,1",
    ot_text_kurz: "...und aus Ägypten habe ich meinen Sohn gerufen.",
    ot_zeitraum: "ca. 750 v. Chr.",
    nt_stelle: "Matthäus 2,15",
    nt_text_kurz: "...aus Ägypten habe ich meinen Sohn gerufen.",
    kommentar: "Jesus wiederholte die Geschichte Israels in seinem eigenen Leben. Seine Rückkehr aus Ägypten symbolisiert den Neuanfang und die Befreiung, die er bringt.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Hosea11%2C1"],
    tags: ["Flucht", "Ägypten", "Sohn"]
  },
  {
    id: 22,
    kategorie: ProphecyCategory.GEBURT,
    beschreibung: "Anbetung und Geschenke von Königen.",
    ot_stelle: "Psalm 72,10",
    ot_text_kurz: "Die Könige von Tarsis ... sollen Geschenke bringen.",
    ot_zeitraum: "ca. 950 v. Chr.",
    nt_stelle: "Matthäus 2,11",
    nt_text_kurz: "Da taten sie ihre Schätze auf und schenkten ihm Gold, Weihrauch und Myrrhe.",
    kommentar: "Bereits als Kleinkind wurde Jesus als König der Welt anerkannt. Die Geschenke der Weisen weisen auf seine göttliche, königliche und leidende Rolle hin.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Psalm72%2C10"],
    tags: ["Weise", "Anbetung", "Geschenke"]
  },
  {
    id: 23,
    kategorie: ProphecyCategory.DIENST,
    beschreibung: "Der Geist der Weisheit und Stärke ruht auf ihm.",
    ot_stelle: "Jesaja 11,2",
    ot_text_kurz: "Auf ihm wird ruhen der Geist des HERRN, der Geist der Weisheit und des Verstandes...",
    ot_zeitraum: "ca. 700 v. Chr.",
    nt_stelle: "Lukas 4,18",
    nt_text_kurz: "Der Geist des Herrn ist auf mir, weil er mich gesalbt hat, den Armen das Evangelium zu verkünden...",
    nt_2_stelle: "Mk 1,10; Lk 4,14; Lk 4,18",
    nt_2_text_kurz: "„Und alsbald, als er aus dem Wasser stieg, sah er, dass sich der Himmel auftat und der Geist wie eine Taube auf ihn herabfuhr.“ (Markus 1,10) und „Und Jesus kehrte in der Kraft des Geistes zurück nach Galiläa…“ (Lukas 4,14) Und er liest über sich selbst: „Der Geist des Herrn ist auf mir, weil er mich gesalbt hat…“ (Lukas 4,18; vgl. Jesaja 61,1)",
    kommentar: "Die Salbung mit dem Heiligen Geist ist die göttliche Bestätigung für Jesu Dienst. Er wirkte nicht aus eigener Kraft, sondern in der vollen Autorität und Kraft des dreieinigen Gottes.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Lukas4%2C18"],
    tags: ["Heiliger Geist", "Salbung", "Kraft"]
  },
  {
    id: 24,
    kategorie: ProphecyCategory.DIENST,
    beschreibung: "Dienst in Galiläa: Licht am See.",
    ot_stelle: "Jesaja 8,23",
    ot_text_kurz: "...so wird er in der künftigen Zeit das Land am See zu Ehren bringen.",
    ot_zeitraum: "ca. 735 v. Chr.",
    nt_stelle: "Matthäus 4,12-16",
    nt_text_kurz: "...das Land Sebulon und das Land Naphtali, am Weg zum See... das Volk, das in Finsternis saß, hat ein großes Licht gesehen.",
    kommentar: "Gott beginnt sein Heilswerk oft dort, wo die Menschen es am wenigsten erwarten. Galiläa galt als geistlich dunkel, doch genau dort strahlte das Licht des Evangeliums zuerst auf.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Jesaja8%2C23"],
    tags: ["Galiläa", "Licht", "Evangelium"]
  },
  {
    id: 25,
    kategorie: ProphecyCategory.DIENST,
    beschreibung: "Er wirkt Wunder: Blinde sehen, Taube hören.",
    ot_stelle: "Jesaja 35,5-6",
    ot_text_kurz: "Dann werden die Augen der Blinden aufgetan und die Ohren der Tauben geöffnet werden.",
    ot_zeitraum: "ca. 700 v. Chr.",
    nt_stelle: "Matthäus 11,5",
    nt_text_kurz: "Blinde sehen und Lahme gehen, Aussätzige werden rein und Taube hören...",
    kommentar: "Jesu Wunder waren Zeichen der anbrechenden Königsherrschaft Gottes. Sie zeigen seine Macht über die Folgen des Sündenfalls und seine Barmherzigkeit gegenüber den Leidenden.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Jesaja35%2C5"],
    tags: ["Wunder", "Heilung", "Vollmacht"]
  },
  {
    id: 26,
    kategorie: ProphecyCategory.DIENST,
    beschreibung: "Er predigt in Gleichnissen.",
    ot_stelle: "Psalm 78,2",
    ot_text_kurz: "Ich will meinen Mund auftun in Gleichnissen.",
    ot_zeitraum: "ca. 1000 v. Chr.",
    nt_stelle: "Matthäus 13,34-35",
    nt_text_kurz: "Dies alles redete Jesus in Gleichnissen zur Volksmenge.",
    kommentar: "Gleichnisse verbergen die Wahrheit vor den Hochmütigen und offenbaren sie den Demütigen. Jesus nutzte sie, um die tiefen Geheimnisse des Reiches Gottes verständlich zu machen.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Psalm78%2C2"],
    tags: ["Lehre", "Gleichnisse", "Weisheit"]
  },
  {
    id: 27,
    kategorie: ProphecyCategory.DIENST,
    beschreibung: "Sanftmut: Das geknickte Rohr.",
    ot_stelle: "Jesaja 42,2-3",
    ot_text_kurz: "...das geknickte Rohr wird er nicht zerbrechen.",
    ot_zeitraum: "ca. 700 v. Chr.",
    nt_stelle: "Matthäus 12,19-20",
    nt_text_kurz: "Er wird nicht streiten noch schreien ... das geknickte Rohr wird er nicht zerbrechen.",
    kommentar: "Jesu Sanftmut ist eine Einladung an alle Mühseligen und Beladenen. Er stößt die Schwachen nicht weg, sondern richtet sie auf und gibt ihnen neue Hoffnung.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Jesaja42%2C2"],
    tags: ["Sanftmut", "Trost", "Gnade"]
  },
  {
    id: 28,
    kategorie: ProphecyCategory.DIENST,
    beschreibung: "Licht für die Heidenvölker.",
    ot_stelle: "Jesaja 42,6",
    ot_text_kurz: "...zum Licht für die Heiden.",
    ot_zeitraum: "ca. 700 v. Chr.",
    nt_stelle: "Lukas 2,32",
    nt_text_kurz: "...ein Licht zur Erleuchtung der Heiden.",
    kommentar: "Der Messias ist nicht nur für Israel gekommen. Sein Licht durchbricht die geistliche Finsternis aller Völker und bietet jedem Menschen den Weg zum Vater an.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Jesaja42%2C6"],
    tags: ["Heiden", "Weltweit", "Licht"]
  },
  {
    id: 29,
    kategorie: ProphecyCategory.DIENST,
    beschreibung: "Eifer für das Haus Gottes.",
    ot_stelle: "Psalm 69,10",
    ot_text_kurz: "Denn der Eifer um dein Haus hat mich verzehrt.",
    ot_zeitraum: "ca. 1000 v. Chr.",
    nt_stelle: "Johannes 2,17",
    nt_text_kurz: "Da dachten seine Jünger daran, dass geschrieben steht: Der Eifer um dein Haus hat mich verzehrt.",
    kommentar: "Jesu Reinigung des Tempels zeigt seine Heiligkeit und seinen brennenden Wunsch, dass die Anbetung Gottes rein und unverfälscht bleibt. Er ist das wahre Zentrum der Anbetung.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Psalm69%2C10"],
    tags: ["Tempel", "Heiligkeit", "Eifer"]
  },
  {
    id: 30,
    kategorie: ProphecyCategory.DIENST,
    beschreibung: "Heilung der zerbrochenen Herzen.",
    ot_stelle: "Jesaja 61,1",
    ot_text_kurz: "...zu verbinden, die zerbrochenen Herzens sind.",
    ot_zeitraum: "ca. 700 v. Chr.",
    nt_stelle: "Lukas 4,18",
    nt_text_kurz: "...er hat mich gesandt, zu heilen, die zerbrochenen Herzens sind.",
    kommentar: "Jesus begegnet uns in unserer tiefsten Not. Er heilt nicht nur körperliche Gebrechen, sondern auch die seelischen Wunden, die uns von Gott und Menschen trennen.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Jesaja61%2C1"],
    tags: ["Heilung", "Seelsorge", "Barmherzigkeit"]
  },
  {
    id: 31,
    kategorie: ProphecyCategory.DIENST,
    beschreibung: "Er ist sündlos und ohne Betrug.",
    ot_stelle: "Jesaja 53,9",
    ot_text_kurz: "...obwohl er kein Unrecht getan hat und kein Betrug in seinem Mund gewesen ist.",
    ot_zeitraum: "ca. 700 v. Chr.",
    nt_stelle: "1. Petrus 2,22",
    nt_text_kurz: "Er, der keine Sünde getan hat und in dessen Mund kein Betrug gefunden worden ist.",
    kommentar: "Jesu Sündlosigkeit ist das Fundament unserer Erlösung. Nur ein vollkommen Gerechter konnte die Strafe für die Ungerechten stellvertretend auf sich nehmen.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Jesaja53%2C9"],
    tags: ["Sündlos", "Gerechtigkeit", "Wahrheit"]
  },
  {
    id: 32,
    kategorie: ProphecyCategory.LEIDEN,
    beschreibung: "Der Stein, den die Bauleute verwarfen.",
    ot_stelle: "Psalm 118,22",
    ot_text_kurz: "Der Stein, den die Bauleute verworfen haben, ist zum Eckstein geworden.",
    ot_zeitraum: "Unbekannt",
    nt_stelle: "Matthäus 21,42",
    nt_text_kurz: "Habt ihr noch nie in den Schriften gelesen: Der Stein, den die Bauleute verworfen haben...?",
    kommentar: "Obwohl die religiösen Führer Jesus ablehnten, hat Gott ihn zum tragenden Fundament seiner Gemeinde gemacht. Wer auf diesen Stein baut, wird nicht zuschanden werden.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Psalm118%2C22"],
    tags: ["Eckstein", "Ablehnung", "Gemeinde"]
  },
  {
    id: 33,
    kategorie: ProphecyCategory.LEIDEN,
    beschreibung: "Von seinem Volk abgelehnt.",
    ot_stelle: "Jesaja 53,3",
    ot_text_kurz: "Verachtet war er und verlassen von den Menschen.",
    ot_zeitraum: "ca. 700 v. Chr.",
    nt_stelle: "Johannes 1,11",
    nt_text_kurz: "Er kam in sein Eigentum, und die Seinen nahmen ihn nicht auf.",
    kommentar: "Die Tragik der Ablehnung durch sein eigenes Volk macht die Weite der Gnade Gottes deutlich: Durch Israels Fall kam das Heil zu allen anderen Völkern.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Jesaja53%2C3"],
    tags: ["Ablehnung", "Israel", "Eigentum"]
  },
  {
    id: 34,
    kategorie: ProphecyCategory.LEIDEN,
    beschreibung: "Verrat durch einen engen Freund.",
    ot_stelle: "Psalm 41,10",
    ot_text_kurz: "Auch mein Freund, dem ich vertraute ... hat die Ferse gegen mich erhoben.",
    ot_zeitraum: "ca. 1000 v. Chr.",
    nt_stelle: "Johannes 13,18",
    nt_text_kurz: "...damit die Schrift erfüllt würde: Der mein Brot isst, hat die Ferse gegen mich erhoben.",
    kommentar: "Der Schmerz des Verrats durch einen Vertrauten zeigt die tiefe Einsamkeit Jesu in seinem Leiden. Er trug selbst den Schmerz zerbrochener Beziehungen für uns.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Psalm41%2C10"],
    tags: ["Verrat", "Freundschaft", "Einsamkeit"]
  },
  {
    id: 35,
    kategorie: ProphecyCategory.LEIDEN,
    beschreibung: "Verlassen von den Jüngern.",
    ot_stelle: "Sacharja 13,7",
    ot_text_kurz: "Schlage den Hirten, und die Schafe werden sich zerstreuen!",
    ot_zeitraum: "ca. 520 v. Chr.",
    nt_stelle: "Markus 14,50",
    nt_text_kurz: "Da verließen ihn alle und flohen.",
    kommentar: "In der schwersten Stunde war Jesus allein. Seine Jünger flohen, doch er blieb standhaft, um den Willen des Vaters bis zum Ende zu erfüllen.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Sacharja13%2C7"],
    tags: ["Flucht", "Hirte", "Schafe"]
  },
  {
    id: 36,
    kategorie: ProphecyCategory.LEIDEN,
    beschreibung: "Falsche Zeugen gegen ihn.",
    ot_stelle: "Psalm 35,11",
    ot_text_kurz: "Es treten freche Zeugen auf; sie verhören mich über Dinge, von denen ich nichts weiß.",
    ot_zeitraum: "ca. 1000 v. Chr.",
    nt_stelle: "Matthäus 26,60",
    nt_text_kurz: "...Zuletzt aber traten zwei falsche Zeugen herzu.",
    kommentar: "Die Ungerechtigkeit des Prozesses gegen Jesus macht seine Gerechtigkeit umso strahlender. Er wurde durch Lügen verurteilt, damit wir durch seine Wahrheit frei werden.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Psalm35%2C11"],
    tags: ["Lüge", "Prozess", "Ungerechtigkeit"]
  },
  {
    id: 37,
    kategorie: ProphecyCategory.LEIDEN,
    beschreibung: "Geschlagen und angespuckt.",
    ot_stelle: "Jesaja 50,6",
    ot_text_kurz: "...mein Angesicht verbarg ich nicht vor Schmach und Speichel.",
    ot_zeitraum: "ca. 700 v. Chr.",
    nt_stelle: "Matthäus 26,67",
    nt_text_kurz: "Da spuckten sie ihm ins Angesicht und schlugen ihn mit Fäusten.",
    kommentar: "Jesus ertrug die tiefste Schande und körperliche Misshandlung ohne Murren. Seine Liebe zu uns war stärker als der Schmerz und die Erniedrigung durch seine Geschöpfe.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Jesaja50%2C6"],
    tags: ["Spott", "Schande", "Geduld"]
  },
  {
    id: 38,
    kategorie: ProphecyCategory.LEIDEN,
    beschreibung: "Ohne Grund gehasst.",
    ot_stelle: "Psalm 69,5",
    ot_text_kurz: "Die mich ohne Ursache hassen, sind mehr als die Haare auf meinem Haupt.",
    ot_zeitraum: "ca. 1000 v. Chr.",
    nt_stelle: "Johannes 15,25",
    nt_text_kurz: "...Sie haben mich ohne Grund gehasst.",
    kommentar: "Der Hass der Welt gegen Jesus richtet sich eigentlich gegen Gott selbst. Jesus trug diesen unbegründeten Hass, um uns mit dem Vater zu versöhnen.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Psalm69%2C5"],
    tags: ["Hass", "Welt", "Ursache"]
  },
  {
    id: 39,
    kategorie: ProphecyCategory.TOD,
    beschreibung: "Unter Verbrecher gerechnet.",
    ot_stelle: "Jesaja 53,12",
    ot_text_kurz: "...und den Übeltätern beigezählt wurde.",
    ot_zeitraum: "ca. 700 v. Chr.",
    nt_stelle: "Markus 15,27-28",
    nt_text_kurz: "Und sie kreuzigten mit ihm zwei Räuber.",
    kommentar: "Jesus nahm den Platz eines Verbrechers ein, damit wir den Platz von Gerechten vor Gott einnehmen können. Er identifizierte sich mit den Sündern bis in den Tod.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Jesaja53%2C12"],
    tags: ["Übeltäter", "Stellvertretung", "Räuber"]
  },
  {
    id: 40,
    kategorie: ProphecyCategory.TOD,
    beschreibung: "Sie würfeln um seine Kleider.",
    ot_stelle: "Psalm 22,19",
    ot_text_kurz: "Sie teilen meine Kleider unter sich und werfen das Los über mein Gewand.",
    ot_zeitraum: "ca. 1000 v. Chr.",
    nt_stelle: "Johannes 19,23-24",
    nt_text_kurz: "...Lasst uns darum losen.",
    kommentar: "Jedes Detail, selbst die Gier der Soldaten um seine Kleidung, war im Voraus bekannt. Es zeigt, dass nichts am Kreuz zufällig geschah.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Psalm22%2C19"],
    tags: ["Kleider", "Los", "Soldaten"]
  },
  {
    id: 41,
    kategorie: ProphecyCategory.TOD,
    beschreibung: "Verspottet am Kreuz.",
    ot_stelle: "Psalm 22,8",
    ot_text_kurz: "Alle, die mich sehen, spotten über mich.",
    ot_zeitraum: "ca. 1000 v. Chr.",
    nt_stelle: "Matthäus 27,39",
    nt_text_kurz: "Die aber vorübergingen, lästerten ihn.",
    kommentar: "Der Spott der Menschen war die letzte Prüfung seiner Geduld. Er hätte vom Kreuz steigen können, doch seine Liebe hielt ihn dort fest.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Psalm22%2C8"],
    tags: ["Spott", "Lästerung", "Liebe"]
  },
  {
    id: 42,
    kategorie: ProphecyCategory.TOD,
    beschreibung: "Er betet für seine Feinde.",
    ot_stelle: "Jesaja 53,12",
    ot_text_kurz: "...und für die Übeltäter gebetet.",
    ot_zeitraum: "ca. 700 v. Chr.",
    nt_stelle: "Lukas 23,34",
    nt_text_kurz: "Jesus aber sprach: Vater, vergib ihnen, denn sie wissen nicht, was sie tun!",
    kommentar: "Jesu erste Worte am Kreuz waren ein Gebet um Vergebung. Dies zeigt das Herz Gottes, das selbst seinen Mördern die Hand zur Versöhnung reicht.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Jesaja53%2C12"],
    tags: ["Gebet", "Vergebung", "Feindesliebe"]
  },
  {
    id: 43,
    kategorie: ProphecyCategory.TOD,
    beschreibung: "Der Schrei der Verlassenheit.",
    ot_stelle: "Psalm 22,2",
    ot_text_kurz: "Mein Gott, mein Gott, warum hast du mich verlassen?",
    ot_zeitraum: "ca. 1000 v. Chr.",
    nt_stelle: "Matthäus 27,46",
    nt_text_kurz: "...Mein Gott, mein Gott, warum hast du mich verlassen?",
    kommentar: "In diesem Moment erlebte Jesus die Hölle – die absolute Trennung von Gott –, damit wir niemals von Gott verlassen werden müssen.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Psalm22%2C2"],
    tags: ["Gottverlassenheit", "Psalm 22", "Gericht"]
  },
  {
    id: 44,
    kategorie: ProphecyCategory.TOD,
    beschreibung: "Durst am Kreuz.",
    ot_stelle: "Psalm 22,16",
    ot_text_kurz: "...und meine Zunge klebt an meinem Gaumen.",
    ot_zeitraum: "ca. 1000 v. Chr.",
    nt_stelle: "Johannes 19,28",
    nt_text_kurz: "...spricht er ...: Mich dürstet!",
    kommentar: "Jesu Durst war real und schmerzhaft. Er, der die Quelle des lebendigen Wassers ist, dürstete, damit unser geistlicher Durst ewig gestillt werden kann.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Psalm22%2C16"],
    tags: ["Durst", "Menschheit", "Leiden"]
  },
  {
    id: 45,
    kategorie: ProphecyCategory.TOD,
    beschreibung: "Seine Seite wird durchbohrt.",
    ot_stelle: "Sacharja 12,10",
    ot_text_kurz: "Sie werden auf mich blicken, den sie durchbohrt haben.",
    ot_zeitraum: "ca. 520 v. Chr.",
    nt_stelle: "Johannes 19,34",
    nt_text_kurz: "...stieß mit einer Lanze in seine Seite.",
    kommentar: "Das ausfließende Blut und Wasser sind Symbole für die Sühnung und Reinigung, die durch Jesu Tod bewirkt wurden. Er wurde für uns durchstochen.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Sacharja12%2C10"],
    tags: ["Lanze", "Blut", "Wasser"]
  },
  {
    id: 46,
    kategorie: ProphecyCategory.TOD,
    beschreibung: "Stellvertretendes Opfer.",
    ot_stelle: "Jesaja 53,5",
    ot_text_kurz: "Doch er wurde um unserer Übertretungen willen durchbohrt.",
    ot_zeitraum: "ca. 700 v. Chr.",
    nt_stelle: "Römer 5,8",
    nt_text_kurz: "...dass Christus für uns gestorben ist, als wir noch Sünder waren.",
    kommentar: "Dies ist der Kern des Evangeliums: Jesus starb nicht für seine Fehler, sondern für unsere. Er tauschte seine Gerechtigkeit gegen unsere Schuld.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Jesaja53%2C5"],
    tags: ["Sühne", "Stellvertretung", "Gnade"]
  },
  {
    id: 47,
    kategorie: ProphecyCategory.AUFERSTEHUNG,
    beschreibung: "Auferstehung am dritten Tag.",
    ot_stelle: "Jona 2,1",
    ot_text_kurz: "...Jona war im Bauch des Fisches drei Tage und drei Nächte.",
    ot_zeitraum: "ca. 760 v. Chr.",
    nt_stelle: "Matthäus 12,40",
    nt_text_kurz: "...so wird der Sohn des Menschen drei Tage und drei Nächte im Schoß der Erde sein.",
    kommentar: "Die Errettung Jonas aus dem Fisch war ein historischer Vorchatten auf Jesu Sieg über das Grab. Der Tod konnte den Autor des Lebens nicht halten.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Jona2%2C1"],
    tags: ["Jona", "Drei Tage", "Sieg"]
  },
  {
    id: 48,
    kategorie: ProphecyCategory.KOENIGTUM,
    beschreibung: "Sitz zur Rechten Gottes.",
    ot_stelle: "Psalm 110,1",
    ot_text_kurz: "Der HERR sprach zu meinem Herrn: Setze dich zu meiner Rechten.",
    ot_zeitraum: "ca. 1000 v. Chr.",
    nt_stelle: "Hebräer 1,3",
    nt_text_kurz: "...hat er sich gesetzt zur Rechten der Majestät in der Höhe.",
    kommentar: "Die Rechten Gottes ist der Platz der höchsten Macht und Ehre. Jesus regiert jetzt über das Universum und bereitet seine Wiederkunft vor.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Psalm110%2C1"],
    tags: ["Macht", "Regierung", "Ehre"]
  },
  {
    id: 49,
    kategorie: ProphecyCategory.KOENIGTUM,
    beschreibung: "Er ist der Sohn Gottes.",
    ot_stelle: "Psalm 2,7",
    ot_text_kurz: "Der HERR hat zu mir gesprochen: Du bist mein Sohn.",
    ot_zeitraum: "ca. 1000 v. Chr.",
    nt_stelle: "Matthäus 3,17",
    nt_text_kurz: "Dies ist mein geliebter Sohn, an dem ich Wohlgefallen habe.",
    kommentar: "Jesu Sohn-Sein beschreibt seine wesensgleiche Natur mit dem Vater. Er ist nicht nur ein Bote, sondern Gott selbst, der uns begegnet.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Psalm2%2C7"],
    tags: ["Sohnschaft", "Gott", "Offenbarung"]
  },
  {
    id: 50,
    kategorie: ProphecyCategory.KOENIGTUM,
    beschreibung: "Priester nach der Weise Melchisedeks.",
    ot_stelle: "Psalm 110,4",
    ot_text_kurz: "Du bist Priester in Ewigkeit nach der Weise Melchisedeks.",
    ot_zeitraum: "ca. 1000 v. Chr.",
    nt_stelle: "Hebräer 5,6",
    nt_text_kurz: "Du bist Priester in Ewigkeit nach der Weise Melchisedeks.",
    kommentar: "Jesu Priestertum ist erhaben über das levitische Gesetz. Er ist König und Priester zugleich, ein vollkommener Vermittler zwischen Gott und Menschen.",
    quelle_links: ["https://www.bibleserver.com/SCH2000/Psalm110%2C4"],
    tags: ["Hohepriester", "Melchisedek", "Vermittler"]
  }
];